### ISSUE TITLE
Minor tidying around use of Bluetooth Comany ID value

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_BLE_Eddystone#7]
I noticed:

- the code makes us of Google's Bluetooth Company ID (`0xfeaa`) but doesn't describe it as such and it's duplicated as a little-endian 16bit value, embedded in a cryptic looking `prefix` string:
   - https://github.com/adafruit/Adafruit_CircuitPython_BLE_Eddystone/blob/d8c43dedbfb19b0ba341dccdf4038848af0ee444/adafruit_ble_eddystone/__init__.py#L46
   - https://github.com/adafruit/Adafruit_CircuitPython_BLE_Eddystone/blob/d8c43dedbfb19b0ba341dccdf4038848af0ee444/adafruit_ble_eddystone/uid.py#L45 and https://github.com/adafruit/Adafruit_CircuitPython_BLE_Eddystone/blob/d8c43dedbfb19b0ba341dccdf4038848af0ee444/adafruit_ble_eddystone/url.py#L98

**Comment by kevinjwalters** [comment]
Improvements around `prefix` feature in https://github.com/adafruit/Adafruit_CircuitPython_BLE/issues/82

**Comment by kevinjwalters** [comment]
`prefix` is deprecated now, https://github.com/adafruit/Adafruit_CircuitPython_BLE/issues/82 with https://github.com/adafruit/Adafruit_CircuitPython_BLE/pull/89 introduces `match_prefixes` to replace it.

**Comment by dhalbert** [comment]
I replaced `prefix` with `match_prefixes` in PR #8 in mid-June. How is the current code?

**Comment by kevinjwalters** [comment]
The current code does use `match_prefixes`. I'd only looked at the issue tickets and assumed incorrectly that hadn't been updated.

**Comment by dhalbert** [comment]
Thanks, I'll close this. I should have noticed this issue was addressed by #8. We deliberately don't ID the company ID, to avoid appearing like an official Google product thing.

Fixed by #8.
